minimum_pre_commit_version: "3.6.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              frontend/src/client/.*|
              backend/app/email-templates/build/.*
          )$
      - id: trailing-whitespace
        exclude: |
          (?x)^(
              frontend/src/client/.*|
              backend/app/email-templates/build/.*
          )$
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: |
          (?x)^(
              frontend/src/client/.*|
              backend/app/email-templates/build/.*
          )$
      - id: fix-byte-order-marker

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.22
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: biome-check
        name: biome check
        entry: biome check --write --config-path=frontend/biome.json --files-ignore-unknown=true --no-errors-on-unmatched
        language: node
        additional_dependencies:
          - "@biomejs/biome@2.5.11"
        types: [text]
        files: ^frontend/
        exclude: ^frontend/src/client/

ci:
  autofix_commit_msg: "[pre-commit.ci] Auto-format"
  autoupdate_commit_msg: "[pre-commit.ci] Autoupdate"
