"""add key_requests and statement_uploads

Revision ID: d8abce57e25d
Revises: af64808ac4b8
Create Date: 2025-01-29 00:05:36.745570

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d8abce57e25d"
down_revision = "af64808ac4b8"
branch_labels = None
depends_on = None


def upgrade():
    # Create key_requests table
    op.create_table(
        "key_requests",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("key_type", sa.String(length=50), nullable=False),
        sa.Column("request_ip", sa.String(length=50), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("timestamp", sa.TIMESTAMP(), server_default=sa.func.now(), nullable=False),
    )

    # Create statement_uploads table
    op.create_table(
        "statement_uploads",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.Column("init_vector", sa.LargeBinary(), nullable=False),
        sa.Column("auth_tag", sa.LargeBinary(), nullable=False),
        sa.Column("client_ip", sa.String(length=50), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("timestamp", sa.TIMESTAMP(), server_default=sa.func.now(), nullable=False),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_downloads",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("platform", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("version", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("client_ip", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_agent", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "downloaded_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="client_downloads_pkey"),
    )
    op.create_table(
        "plugin_downloads",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("plugin_file", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("client_ip", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_agent", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "downloaded_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="plugin_downloads_pkey"),
    )
    # ### end Alembic commands ###
